### ISSUE TITLE
Whenever the rich presence text is too big the program crashes

### ISSUE THREAD

**Issue by howeena** [sajtii/ra_cli#4]
The following code shows up:

```
Traceback (most recent call last):
  File "C:\Users\Howeena\Downloads\RetroAchivments RichPresence\racli.py", line 477, in <module>
    main()
  File "C:\Users\Howeena\Downloads\RetroAchivments RichPresence\racli.py", line 413, in main
    RPC.update(
  File "C:\Users\Howeena\AppData\Roaming\Python\Python312\site-packages\pypresence\presence.py", line 34, in update
    return self.loop.run_until_complete(self.read_output())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Howeena\AppData\Roaming\Python\Python312\site-packages\pypresence\baseclient.py", line 88, in read_output
    raise ServerError(payload["data"]["message"])
pypresence.exceptions.ServerError: Child "activity" fails because child "state" fails because "state" length must be less than or equal to 128 characters long
```

The game I was playing is persona 3
The text that broke the limit was this one: 

> 
>The Journey | Difficulty: Normal | 5/28 | Level: 12 | Persona: Orpheus | Party: Makoto & --- & --- & --- | 💰 27846 | Compendium: 10/169 

Is this fixable?

**Comment by sajtii** [comment]
I am aware of the problem, I have met with it myself. It is not an issue with my code but rather an issue with pypresence or the Discord API not handling it well. There are many issues opened at the pypresence repository related to this, but the developer said that every developer using pypresence must deal with it by themselves. I will figure out something soon.

**Comment by sajtii** [comment]
A temporary fix is ready. For now, I just cut the text at the end if it is too long. imo it is not the best solution, but it does the job.
![uwu](https://github.com/user-attachments/assets/86502bc7-979e-4281-887b-e1a7527d3c58)
